version: "3.9"

services:
  juice-shop:
    image: bkimminich/juice-shop
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"

  recon-ui:
    build:
      context: .
      args:
        INCLUDE_PDF: ${INCLUDE_PDF-false}
    command: ["python", "web_ui.py"]
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - juice-shop
    volumes:
      - ./results:/app/results
    ports:
      - "127.0.0.1:5000:5000"
