[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "reconscript"
version = "0.4.0"
description = "Safe reconnaissance helper for authorized assessments only; use responsibly within agreed scope."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  {name = "Safe Recon Team", email = "security@example.com"}
]
dependencies = [
  "requests>=2.31,<2.32",
  "rich>=13.7,<14",
  "weasyprint>=61.2,<62",
]

[project.optional-dependencies]
dev = [
  "pytest>=7.4,<8",
  "responses>=0.25,<0.26",
  "flake8>=6.1,<7"
]
keywords = ["reconnaissance", "security", "safety"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "License :: OSI Approved :: MIT License",
  "Intended Audience :: Information Technology",
  "Topic :: Security",
  "Development Status :: 4 - Beta"
]

[project.urls]
Homepage = "https://example.com/reconscript"
Repository = "https://example.com/reconscript/repo"

[project.scripts]
safe-recon = "reconscript.cli:main"
reconscript = "reconscript.cli:main"

[tool.setuptools]
packages = ["reconscript"]

[tool.setuptools.package-data]
"reconscript" = ["templates/*.html"]

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
