name: ci-matrix

on:
  pull_request:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Run unit tests
        run: pytest -m "not integration" --maxfail=1 --ff
      - name: Upload coverage data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./.coverage*
          if-no-files-found: ignore

  integration:
    runs-on: ubuntu-latest
    needs: build-test
    environment: integration
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.integration == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run integration tests
        env:
          INTEGRATION_SCANME: ${{ secrets.INTEGRATION_SCANME || 'false' }}
        run: pytest -m integration --maxfail=1 --ff
