name: quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt

      - name: Black (check)
        run: black --check .

      - name: Ruff
        run: ruff check .

      - name: Pytest
        run: pytest

      - name: Bandit security scan
        run: bandit -r reconscript
        continue-on-error: true

      - name: pip-audit
        run: pip-audit --requirement requirements.txt
        continue-on-error: true
